vich_uploader:
    db_driver: orm
    mappings:
        decretos:
            uri_prefix:         '%app.path.decretos%'
            upload_destination: '%kernel.project_dir%/public%app.path.decretos%'