easy_admin:
  #    disabled_actions: ['delete']
  site_name: '%env(APP_NAME)%'
  show:
    max_results: 10
  list:
    actions:
      - { name: 'show', icon: 'eye', label: '' }
      - { name: 'edit', icon: 'pencil', label: '' }
    #            - { name: 'delete', icon: 'trash', label: '' }

  design:
    brand_color: '#%env(APP_COLOR)%'
    assets:
      favicon: 'logo_oficial.ico'
    #            templates:
    #                layout: 'easyadmin/default/layout.html.twig'
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
    menu:
      - { label: 'Ver Web', route: 'web_index', icon: 'globe'  }
      - { label: 'Decretos', entity: Decreto, icon: 'file' }
      - { label: 'Resoluciones', entity: Resolucion, icon: 'file' }
      - { label: 'Palabras Clave', entity: PalabraClave, icon: 'key' }
      - { label: 'Usuarios', entity: User, icon: 'user', permission: 'ROLE_ADMIN' }

